export const studentsData = [
    // 10R2
    { name: "Al Saleh, Raman Jamal Hassan", className: "10R2", studentId: "10R2-01", password: "Px7!k9M#q2Lz" },
    { name: "Albrecht, Anna", className: "10R2", studentId: "10R2-02", password: "Bv4@n8D*s5Jp" },
    { name: "Amrein, Saphira Juliana", className: "10R2", studentId: "10R2-03", password: "Rm9!t2G#w7Kx" },
    { name: "Böcker, Fynn", className: "10R2", studentId: "10R2-04", password: "Lq3@y6H*b4Nc" },
    { name: "Bullerdiek, Lennart Fynn", className: "10R2", studentId: "10R2-05", password: "Tv8!x5M#p9Zr" },
    { name: "Dürre, Tayler", className: "10R2", studentId: "10R2-06", password: "Kp2@s7V*m3Fq" },
    { name: "Fiolka, Maya", className: "10R2", studentId: "10R2-07", password: "Xn6!d9B#h5Wj" },
    { name: "Gorani, Adelina", className: "10R2", studentId: "10R2-08", password: "Mz5@r2K*t8Gy" },
    { name: "Griebe, Luca Finn", className: "10R2", studentId: "10R2-09", password: "Yb3!f7J#n4Lv" },
    { name: "Hoppe, Zoe", className: "10R2", studentId: "10R2-10", password: "Qd9@k4M*w2Px" },
    { name: "Krawzow, Liliana", className: "10R2", studentId: "10R2-11", password: "Hf5!p8T#s3Bn" },
    { name: "Mela Ali, Amina", className: "10R2", studentId: "10R2-12", password: "Jn7@t2X*v9Mr" },
    { name: "Melnik, Dennis", className: "10R2", studentId: "10R2-13", password: "Ck4!z6G#h8Lb" },
    { name: "Önel, Mirxan", className: "10R2", studentId: "10R2-14", password: "Vm9@n5P*q2Tr" },
    { name: "Rißland, Lukas", className: "10R2", studentId: "10R2-15", password: "Bc2!w8S#x7Fd" },
    { name: "Salewski, Anthony", className: "10R2", studentId: "10R2-16", password: "Gy5@t3V*k8Pn" },
    { name: "Skala, Julia", className: "10R2", studentId: "10R2-17", password: "Nz9!p4H#v2Mj" },
    { name: "Spangenberg, Zaira Maja Josephine", className: "10R2", studentId: "10R2-18", password: "Xb6@r3K*l7Qw" },
    { name: "Sünnemann, Ole", className: "10R2", studentId: "10R2-19", password: "Df4!m9X#s2Bt" },
    { name: "Sulek, Tom", className: "10R2", studentId: "10R2-20", password: "Gw8@n5J*k3Lr" },
    { name: "Teiwes, Lena-Marie", className: "10R2", studentId: "10R2-21", password: "Vz9!t4P#x7Mk" },
    { name: "Titze, Niclas", className: "10R2", studentId: "10R2-22", password: "Hb3@s6K*y2Ng" },
    { name: "Wahle, Thilo", className: "10R2", studentId: "10R2-23", password: "Jp5!d9W#r4Lv" },
    { name: "Weimann, Daniel", className: "10R2", studentId: "10R2-24", password: "Qx2@t7M*b8Pz" },
    { name: "Zorlu, Nilay", className: "10R2", studentId: "10R2-25", password: "Sn4!k9H#v3Gr" },

    // 10R1
    { name: "Bartels, Ilayda Derya", className: "10R1", studentId: "10R1-01", password: "Fv7!p2X#m9Kz" },
    { name: "Bartram, Mia", className: "10R1", studentId: "10R1-02", password: "Lx4@s8B*w5Nd" },
    { name: "Beichert, Maximilian", className: "10R1", studentId: "10R1-03", password: "Tz9!d4H#v7Mh" },
    { name: "Berauer, Bianka", className: "10R1", studentId: "10R1-04", password: "Bc3@r6K*l2Px" },
    { name: "Braun, Chris", className: "10R1", studentId: "10R1-05", password: "Gn8!t5V#m3Jq" },
    { name: "Bullerdiek, Titus Jonah", className: "10R1", studentId: "10R1-06", password: "Mk6@p9H*x4Rv" },
    { name: "Damm, Sophia", className: "10R1", studentId: "10R1-07", password: "Dq2!w7S#n5Lf" },
    { name: "Dreißigacker, Briony", className: "10R1", studentId: "10R1-08", password: "Vz8@t3P*k7Ny" },
    { name: "Hammer, Amy", className: "10R1", studentId: "10R1-09", password: "Jb5!f9X#s2Mk" },
    { name: "Heine, Fynn", className: "10R1", studentId: "10R1-10", password: "Qp9@n4H*r7Dz" },
    { name: "Kaiser, Julius", className: "10R1", studentId: "10R1-11", password: "Xv4!t8M#j3Gn" },
    { name: "Kurylo, Anastasia", className: "10R1", studentId: "10R1-12", password: "Hf2@s7V*m5Kb" },
    { name: "Mahmoud, Hitham", className: "10R1", studentId: "10R1-13", password: "Nz9!k4L#p2Tx" },
    { name: "Movsesiants, Elene", className: "10R1", studentId: "10R1-14", password: "Cw6@v3P*x8Mj" },
    { name: "Nordmann, Adrian", className: "10R1", studentId: "10R1-15", password: "Rb5!f7J#t4Nq" },
    { name: "Osaj, Justus Timm", className: "10R1", studentId: "10R1-16", password: "Yd9@p4K*v2Xm" },
    { name: "Parkhomenko, Margarita", className: "10R1", studentId: "10R1-17", password: "Hb4!t8S#j5Nr" },
    { name: "Petersen, Jule Charlotte", className: "10R1", studentId: "10R1-18", password: "Jx6@r2M*t9Pv" },
    { name: "Sabsabi, Lana", className: "10R1", studentId: "10R1-19", password: "Qz9!k4H#v2Ln" },
    { name: "Thomsen, Bjarne", className: "10R1", studentId: "10R1-20", password: "Tm8@n5J*b3Kx" },
    { name: "Zworski, Moritz Finn", className: "10R1", studentId: "10R1-21", password: "Fp5!d9X#r2Bt" },

    // 10H
    { name: "Amini, Tamim", className: "10H", studentId: "10H-01", password: "Vz9!t4M#x7Pk" },
    { name: "Azimi, Arezo", className: "10H", studentId: "10H-02", password: "Hb3@s6G*y2Nd" },
    { name: "Bektasevic, Maida", className: "10H", studentId: "10H-03", password: "Jp5!d9W#r4Lv" },
    { name: "Efremidis, Alexis", className: "10H", studentId: "10H-04", password: "Qx2@t7M*b8Pz" },
    { name: "Finger, Joyce", className: "10H", studentId: "10H-05", password: "Sn4!k9H#v3Gr" },
    { name: "Lebjedzinski, Sophie", className: "10H", studentId: "10H-06", password: "Ck2!w8V#m5Nq" },
    { name: "Leikind, Diana", className: "10H", studentId: "10H-07", password: "Tz9@p4K*x2Mb" },
    { name: "Mehmedov, Mert", className: "10H", studentId: "10H-08", password: "Fv7!n8P#q3Jz" },
    { name: "Mhafel, Adel", className: "10H", studentId: "10H-09", password: "Lx4@t5G*b9Nd" },
    { name: "Notthoff, Nijsen", className: "10H", studentId: "10H-10", password: "Bv9!f2S#r7Mk" },
    { name: "Notthoff, Nick", className: "10H", studentId: "10H-11", password: "Dq3@n8H*v5Px" },
    { name: "Özer, Kartal", className: "10H", studentId: "10H-12", password: "Gn7!p4M#k2Tr" },
    { name: "Philipper, Niklas", className: "10H", studentId: "10H-13", password: "Hj9@t3V*x8Pn" },
    { name: "Pörtner, Tim Niklas", className: "10H", studentId: "10H-14", password: "Kb5!d9S#m2Jv" },
    { name: "Pollack, Kimberly", className: "10H", studentId: "10H-15", password: "Nx8@t4P*b3Gy" },
    { name: "Teimori, Asal", className: "10H", studentId: "10H-16", password: "Qz2!k9H#v7Lr" },
    { name: "Topper, Jannik", className: "10H", studentId: "10H-17", password: "Rb9@n5J*k4Tx" },
    { name: "Vogel, Niklas", className: "10H", studentId: "10H-18", password: "Sd4!f7X#m2Bp" },
    { name: "Wirsum, Maxim", className: "10H", studentId: "10H-19", password: "Tv8@p3M*w5Nr" },
];

export const teachersData = [
    { name: "Hofer, Inka", role: "Stellv. Klassenlehrer / Fachlehrer", subject: "Deutsch", password: "Adm!9xH#k2Tz" },
    { name: "Haenicke, Sonja", role: "Klassenlehrer / Fachlehrer", subject: "Mathe", password: "Adm!4vP#q8Nr" },
    { name: "Wischinski", role: "Fachlehrer", subject: "Englisch", password: "Adm!7bM#x5Jp" },
    { name: "Tewes, Tanja", role: "Klassenlehrer", password: "Adm!2sG#h9Lx" },
    { name: "Bähne, Nils", role: "Stellv. Klassenlehrer", password: "Adm!5fK#r3Vz" },
    { name: "Langlott, Christian", role: "Klassenlehrer", password: "Adm!8pD#m6Bg" },
    { name: "Benke, Haider", role: "Stellv. Klassenlehrer", password: "Adm!3nJ#v7Qx" },
];
